project:
  type: book
  # pre-render: quarto render slides/*.qmd
  # resources:
  #   - slides/*.html

book:
  title: "Taller de análisis de mediación causal"
  author: 
    - José Luis Flores Guerrero
    - Omar Silverman
  date: last-modified
  repo-url: https://github.com/sdca-latam/mediation-course
  site-url: https://sdca-latam.github.io/mediation-course
  chapters:
    - index.qmd
    - part: "Preamble"
      chapters:
      - preamble/precourse.qmd
      - preamble/Introduction-to-DAGs.qmd
    - part: "Sessions"
      chapters:
      - sessions/welcome.qmd
      - sessions/motivation.qmd
      - sessions/traditional-mediation-analysis.qmd
      - sessions/causal-mediation-analysis-introduction.qmd
  appendices:
    - appendix/dags.qmd
    - appendix/reading-list.qmd
    
  page-footer:
    center:
      - text: "License: CC BY 4.0"

bibliography:
  - includes/papers.bib
csl: includes/the-american-journal-of-clinical-nutrition.csl


format: html

lang: en
editor:
  markdown:
    wrap: 72
    canonical: true
    
execute:
  freeze: false
