project:
  type: book
  # pre-render: quarto render slides/*.qmd
  # resources:
  #   - slides/*.html

book:
  title: "IDEG Mediation Workshop"
  author: 
    - Jie Zhang
    - Daniel Witte
  date: last-modified
  repo-url: https://github.com/steno-aarhus/IDEG-mediation-course
  site-url: https://steno-aarhus.github.io/IDEG-mediation-course
  chapters:
    - index.qmd
    - part: "Preamble"
      chapters:
      - preamble/precourse.qmd
      - preamble/Introduction-to-DAGs.qmd
    - part: "Sessions"
      chapters:
      - sessions/welcome.qmd
      - sessions/motivation.qmd
      - sessions/traditional-mediation-analysis.qmd
      - sessions/causal-mediation-analysis-introduction.qmd
  appendices:
    - appendix/dags.qmd
    - appendix/reading-list.qmd
    
  page-footer:
    center:
      - text: "License: CC BY 4.0"

bibliography:
  - includes/papers.bib
csl: includes/the-american-journal-of-clinical-nutrition.csl


format: html

editor:
  markdown:
    wrap: 72
    canonical: true
